### ISSUE TITLE
lama-refine 

### ISSUE THREAD

**Issue by mldemox** [geomagical/GeoSynth#3]
Thank you for your work, can you please provide the pre-trained model weights for the lama-refine

**Comment by ankuPRK** [comment]
Hi @mldemox, the repository for lama-with-refiner is this one: https://github.com/geomagical/lama-with-refiner

The refiner works by inference on pre-trained models, we haven't trained any new model. You can just directly use the Big-Lama weights, and pass `--refine=True`, as mentioned here: https://github.com/geomagical/lama-with-refiner#inference-

```
python3 bin/predict.py refine=True model.path=$(pwd)/big-lama indir=$(pwd)/LaMa_test_images outdir=$(pwd)/output
```

**Comment by BrianPugh** [comment]
It should also be noted that the [geomagical/lama-with-refiner](https://github.com/geomagical/lama-with-refiner) repository has been merged into the official [advimman/lama](https://github.com/advimman/lama) repo. Please take any further discussion into that repository.
